var GAME_LEVELS = [
   ["                                                                                ",
   "                                                                                ",
   "                                                                         x      ",
   "                                                                         x      ",
   "                                                                         x      ",
   "                                                                         x      ",
   "                                                                         x      ",
   "                                                                         x      ",
   "                                                                      ooox      ",
   "                                                                     xxxxx      ",
   "                                             ooo                  ooox          ",
   "                                            xxxxx                xxxxx          ",
   "  xx                                                             x              ",
   "  x                                            S              oooxTTTTTTTTTTTTTT",
   "  x                           2       oo              3      xxxxx!!!!!!!!!!!!!!",
   "  x         1                        xxxx    S               x!!!!!!!!!!!!!!!!!!",
   "  x  @             ooo                                       x!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              xTTTx                                             ",
   "                              x!!!x                                             ",
   "                              x!!!x                                             ",
   "                              xxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["x                       x",
   "x                       x",
   "x                       x",
   "x                       x",
   "xxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                       x",
   "x                       x",
   "x               oo      x",
   "x                       x",
   "x                       x",
   "x              xxxx     x",
   "x                       x",
   "x                       x",
   "x          o            x",
   "x          x            x",
   "x                       x",
   "x                       x",
   "x      o                x",
   "x      x                x",
   "x                       x",
   "x                       x",
   "x                       x",
   "xxxx                    x",
   "x           o           x",
   "x                       x",
   "x                       x",
   "x    xxxxx  o           x",
   "x                       x",
   "x                       x",
   "x                       x",
   "x             xxxxx     x",
   "x                       x",
   "x                       x",
   "x                      ox",
   "x                      xx",
   "x                       x",
   "x                       x",
   "x                      ox",
   "x                     xxx",
   "x                       x",
   "x                       x",
   "x                      ox",
   "x                    xxxx",
   "x                       x",
   "x                       x",
   "x                      ox",
   "x                   xxxxx",
   "x                       x",
   "x                oo     x",
   "x                       x",
   "x               xxxx    x",
   "x                       x",
   "x                       x",
   "x       ooo             x",
   "x      xxxxx            x",
   "x                       x",
   "x                       x",
   "xoo                     x",
   "xxx                     x",
   "x      oo  oo           x",
   "x                       x",
   "x                       x",
   "x    xx  xx  xx         x",
   "x                       x",
   "x                       x",
   "x                   ooo x",
   "x                  xxxxxx",
   "x          ooo          x",
   "x                       x",
   "x                       x",
   "x         xxxxx         x",
   "x   ooo                 x",
   "x                       x",
   "x                       x",
   "x  xxxxx                x",
   "x            ooo        x",
   "x                       x",
   "x                       x",
   "x           xxxxx       x",
   "x    oo                 x",
   "x                       x",
   "x                       x",
   "x   xxxx                x",
   "x            oo         x",
   "x                       x",
   "xoo                     x",
   "xxx         xxxx        x",
   "x                       x",
   "x                       x",
   "x                    o  x",
   "x                  xxxxxx",
   "x                       x",
   "x                       x",
   "x           oo          x",
   "x          xxxx         x",
   "x                       x",
   "x                       x",
   "x   oo                  x",
   "x  xxxx                 x",
   "x                       x",
   "x                       x",
   "x          ooo          x",
   "x         xxxxx         x",
   "x                       x",
   "x                    oo x",
   "x                   xxxxx",
   "x                       x",
   "x              @        x",
   "xxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                       x",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xRRRRRRRRRRRRRRRRRRRRRRRx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "  xxxxxxxxxxxxxxxx                                                                                                ",
   "  x              x                                                                                                ",
   "  x              x                                        xxxxxxxxxxxxxxxxxxxx                                    ",
   "  x              x                                        x                  x                                    ",
   "  x              x                                        x                  x                                    ",
   "  x              x                                        x     oo           x                                    ",
   "  xxxxx      xxxxx                                        x       xxxxxxx    xxxxxxxxxxxxx                        ",
   "      x      x                                            x =   xxx     x                x                        ",
   "      x      x                                            x       x     x  o             x                        ",
   "      x      x                                            xoo     x     x  o             x                        ",
   "      x      x                                            x       x     x  o  e          x                        ",
   "      x =    x                                            xxx  =  x     x  o             x                        ",
   "      x      x                                            x       x     xxxx   xxxxxxxxxxxxxx                     ",
   "      x      x                                            x     oox        x                x                     ",
   "      x      x                                            x       x        x  o             x                     ",
   "      x      x                                            x   = xxx        x  o             x                     ",
   "      x     =x                xxxxxxxxxxxxxxxxxxxxxxx     x       x        x  o  e          x                     ",
   "      x      x                x                     x     xoo     x        x  o             x                     ",
   "      x      x                x       |          |  x     x       x        xxxx   xxxxxxxxxxxxxx                  ",
   "      x      x                x                     x     xxx=    x           x                x                  ",
   "      x =    x                x                     x     x       x           x  o             x                  ",
   "      x      xxxxxxxxxxxxxxxxxx                     xxxxxxx     oox           x  o             x                  ",
   "      x      |                                                    x           x  o  e          x                  ",
   "      x                |                                        xxx           x  o             x                  ",
   "      x                                                           x           xxxx  xxxxxxxxxxxx                  ",
   "      x        oo | oo   oo     |  o     o  |  o                  x              x  x                             ",
   "      x                     |                                     x              x  x                             ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxTTTxxxTTTxxxTTTxxxTTTxxxxxxxxxxxxxxx              x  x                             ",
   "                              x!!!!!!!!!!!!!!!!!!!!!x                            x  x                             ",
   "                              x!!!!!!!!!!!!!!!!!!!!!x                            x  x                             ",
   "                              xxxxxxxxxxxxxxxxxxxxxxx                            x  x                             ",
   "                                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxx  x                             ",
   "                                                      x                         xx  x                             ",
   "                                                      xS                     S  xx  x                             ",
   "                                                      x                S        xx  x                             ",
   "                                                      x       ooo             o xx  x                             ",
   "                                                      x                         xx  x                             ",
   "                                                      x      xxxxx           xxxxx  x                             ",
   "                                                      x    S                     x  x                             ",
   "                                                      x             S  ooo       x  x                             ",
   "                                                      x                             x                             ",
   "                                                      x               xxxxx         x                             ",
   "                                                      x ooo     S                   x                             ",
   "                                                      x                      S     ox                             ",
   "                                                      xxxxxx                     @  x                             ",
   "                                                      xTTTTTTTTTTTTTTTTTTTTTTTTxxxxxx                             ",
   "                                                      x!!!!!!!!!!!!!!!!!!!!!!!!!x                                 ",
   "                                                      x!!!!!!!!!!!!!!!!!!!!!!!!!x                                 ",
   "                                                      xxxxxxxxxxxxxxxxxxxxxxxxxxx                                 ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x               |||         |||         |||   S    S    S    S     x            x         x            o x  ",
   "  x                                             S                    x            x         xxxxxxx        x  ",
   "  x                                                                  x  xxxxxxxx  xxxxx  x  x     x  xxxxxxx  ",
   "  x                                                                  x         x  x      x  x     x        x  ",
   "  x                                                                  x         x  x      x  x  x  x        x  ",
   "  x                                                       S          xxxxxxxx  x  x  xxxxx  x  x  xxxxxxx  x  ",
   "  x        4                                         S    S    S               x     x         x           x  ",
   "  x     @               |||         |||  B           S    S    S               x     x         x           x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxTxxxxxxxxxxxxxxxxxxTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT!TTTTTTTTTTTTTTTTTT!TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x5   F                           F                    x",
   "x                                                     x",
   "x                 F                          F        x",
   "x                                                     x",
   "x                                                     x",
   "x                                                     x",
   "x                                                     x",
   "x                                                     x",
   "x                                                     x",
   "x     @                                               x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
